networks:
  prod:
  backend:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - prod

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - prod
      - backend
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend
    networks:
      - prod
  
  db:
    image: postgres:16.4
    container_name: lumea_database
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - backend